### ISSUE TITLE
Missing feature - taking back the exempted status

### ISSUE THREAD

**Issue by killertilapia** [COE11-USTP-CEA/Calling-Card-AJA#6]
Guys, someone pointed out to me that I forgot to check the "edit" feature of your project.

I ran the project again and confirmed that it doesn't have that "edit" feature - I tried all the links in the project. As impressive the extra features were, the login and sort, it still didn't meet the minimum standard that I set for the project. 

I'm sorry but I'm taking back the exempted status I gave the team. 

Good luck on Tuesday.

**Comment by wacanam** [comment]
Its okay sir.... We will try our best and I'm going to work on it before the final cloning and  hopefully we could comply all the minimum requirements of this projects...

**Comment by wacanam** [comment]
@killertilapia  sir jay.. same me sa Javastated walay edit nga feature..nobody will exempted hihi

**Comment by wacanam** [comment]
@killertilapia .The team cannot accept that the other team with the same lacking would be exempted as well....
 javastated with exempted status also lack the edit feature..
we clone many times their repo, ran and we manually check it  sa github but wala jud silay edit sir.... this means nga wala pud nila na comply ang minimum requirments.
